a few bits tried to escape, but we caught them

diff --git a/functions.d/F06-security b/functions.d/F06-security
--- a/functions.d/F06-security
+++ b/functions.d/F06-security
@@ -602,6 +602,14 @@ function generateEntropyFile
     [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} -> enter";
     [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "Provided arguments: ${*}";
 
+    [ -z "${RANDOM_GENERATOR}" ] && typeset RANDOM_GENERATOR="/dev/random";
+    [ -z "${ENTROPY_FILE}" ] && typeset ENTROPY_FILE="${HOME}/.etc/entropy";
+    [ -z "${ENTROPY_FILE_SIZE}" ] && typeset -i ENTROPY_FILE_SIZE=16384;
+
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "RANDOM_GENERATOR -> ${RANDOM_GENERATOR}";
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "ENTROPY_FILE -> ${ENTROPY_FILE}";
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "ENTROPY_FILE_SIZE -> ${ENTROPY_FILE_SIZE}";
+
     typeset -i ERROR_COUNT=0;
     typeset ENTROPY_FILE_NAME=${ENTROPY_FILE##*/};
     typeset ENTROPY_BACKUP_FILE=${ENTROPY_FILE_NAME}.${DATESYS};
@@ -658,6 +666,8 @@ function generateEntropyFile
 
             continue;
         fi
+
+        break;
     done < ${RANDOM_GENERATOR};
 
     writeLogEntry "INFO" "${METHOD_NAME}" "${0}" "${LINENO}" "Entropy file generated. Modifying permissions and removing backup.";
@@ -1601,3 +1611,151 @@ function passwordRepository
     return ${RETURN_CODE};
 }
 
+#=====  FUNCTION  =============================================================
+#          NAME:  generateKeyPair
+#   DESCRIPTION:  Generate an RSA public/private keypair via OpenSSL
+#    PARAMETERS:  Filename, key size
+#       RETURNS:  0 regardless of result.
+#==============================================================================
+function generateKeyPair
+{
+    trap '[ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] || set +x; [ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set +v; set -o noclobber' INT TERM EXIT;
+
+    [ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] && set -x || set +x;
+    [ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set -v || set +v;
+
+    set +o noclobber;
+    typeset METHOD_NAME="${0}#${FUNCNAME[0]}";
+    typeset -i RETURN_CODE=0;
+
+    [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} START: $(date +"${TIMESTAMP_OPTS}")";
+    [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i START_EPOCH=$(date +"%s");
+
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} -> enter";
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "Provided arguments: ${*}";
+
+    if [ ${#} -eq 0 ]
+    then
+        RETURN_CODE=3;
+
+        writeLogEntry "STDERR" "${METHOD_NAME} - Generate an RSA public/private keypair via OpenSSL";
+        writeLogEntry "STDERR" "Usage: ${METHOD_NAME} [ file ] [ keysize ]
+            -> The filename in which to save the generated keypair
+            -> The size of the keypair to generate.
+                -> If not specified, 4096 is utilized.
+                -> If specified but less than 2048, 2048 is utilized.";
+
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "RETURN_CODE -> ${RETURN_CODE}";
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} -> exit";
+
+        [ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] && set +x;
+        [ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set +v;
+
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i END_EPOCH=$(date +"%s");
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i RUNTIME=$(( START_EPOCH - END_EPOCH ));
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} TOTAL RUNTIME: $(( RUNTIME / 60 )) MINUTES, TOTAL ELAPSED: $(( RUNTIME % 60 )) SECONDS";
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} END: $(date +"${TIMESTAMP_OPTS}")";
+
+        [ ! -z "${KEYFILE}" ] && unset -v KEYFILE;
+        [ ! -z "${KEYSIZE}" ] && unset -v KEYSIZE;
+        [ ! -z "${RET_CODE}" ] && unset -v RET_CODE;
+        [ ! -z "${METHOD_NAME}" ] && unset -v METHOD_NAME;
+
+        return ${RETURN_CODE};
+    fi
+
+    typeset KEYFILE="${1}";
+    [ ${#} -ne 2 ] && typeset -i KEYSIZE=4096 || typeset -i KEYSIZE=${2};
+    [ ${KEYSIZE} -lt 2048 ] && typeset -i KEYSIZE=2048;
+
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "KEYFILE -> KEYFILE";
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "KEYSIZE -> KEYSIZE";
+
+    ## generate the keypair
+    /usr/bin/env openssl genrsa -out ${KEYFILE}.pem ${KEYSIZE} -outform pem;
+    typeset -i RET_CODE=${?};
+
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "RET_CODE -> RET_CODE";
+
+    if [ -z ${RET_CODE} ] || [ ${RET_CODE} -ne 0 ] || [ ! -s "${KEYFILE}.pem" ]
+    then
+        typeset -i RETURN_CODE=1;
+
+        writeLogEntry "ERROR" "${METHOD_NAME}" "${0}" "${LINENO}" "Failed to create a private keyfile. Cannot continue.";
+        writeLogEntry "STDERR" "${METHOD_NAME}" "${0}" "${LINENO}" "Failed to create a private keyfile. Cannot continue.";
+
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "RETURN_CODE -> ${RETURN_CODE}";
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} -> exit";
+
+        [ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] && set +x;
+        [ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set +v;
+
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i END_EPOCH=$(date +"%s");
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i RUNTIME=$(( START_EPOCH - END_EPOCH ));
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} TOTAL RUNTIME: $(( RUNTIME / 60 )) MINUTES, TOTAL ELAPSED: $(( RUNTIME % 60 )) SECONDS";
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} END: $(date +"${TIMESTAMP_OPTS}")";
+
+        [ ! -z "${KEYFILE}" ] && unset -v KEYFILE;
+        [ ! -z "${KEYSIZE}" ] && unset -v KEYSIZE;
+        [ ! -z "${RET_CODE}" ] && unset -v RET_CODE;
+        [ ! -z "${METHOD_NAME}" ] && unset -v METHOD_NAME;
+
+        return ${RETURN_CODE};
+    fi
+
+    ## fix permissions
+    chmod 600 ${KEYFILE}.pem;
+
+    /usr/bin/env openssl rsa -in ${KEYFILE}.pem -out ${KEYFILE}.pub -pubout -outform pem;
+    typeset -i RET_CODE=${?};
+
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "RET_CODE -> RET_CODE";
+
+    if [ -z ${RET_CODE} ] || [ ${RET_CODE} -ne 0 ] || [ ! -s "${KEYFILE}.pub" ]
+    then
+        typeset -i RETURN_CODE=1;
+
+        writeLogEntry "ERROR" "${METHOD_NAME}" "${0}" "${LINENO}" "Failed to create a public keyfile from the given private key.";
+        writeLogEntry "STDERR" "${METHOD_NAME}" "${0}" "${LINENO}" "Failed to create a public keyfile from the given private key.";
+
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "RETURN_CODE -> ${RETURN_CODE}";
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} -> exit";
+
+        [ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] && set +x;
+        [ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set +v;
+
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i END_EPOCH=$(date +"%s");
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i RUNTIME=$(( START_EPOCH - END_EPOCH ));
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} TOTAL RUNTIME: $(( RUNTIME / 60 )) MINUTES, TOTAL ELAPSED: $(( RUNTIME % 60 )) SECONDS";
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} END: $(date +"${TIMESTAMP_OPTS}")";
+
+        [ ! -z "${KEYFILE}" ] && unset -v KEYFILE;
+        [ ! -z "${KEYSIZE}" ] && unset -v KEYSIZE;
+        [ ! -z "${RET_CODE}" ] && unset -v RET_CODE;
+        [ ! -z "${METHOD_NAME}" ] && unset -v METHOD_NAME;
+
+        return ${RETURN_CODE};
+    fi
+
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "RET_CODE -> ${RET_CODE}";
+
+    typeset -i RETURN_CODE=${RET_CODE};
+
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "RETURN_CODE -> ${RETURN_CODE}";
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} -> exit";
+
+    [ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] && set +x;
+    [ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set +v;
+
+    [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i END_EPOCH=$(date +"%s");
+    [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i RUNTIME=$(( START_EPOCH - END_EPOCH ));
+    [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} TOTAL RUNTIME: $(( RUNTIME / 60 )) MINUTES, TOTAL ELAPSED: $(( RUNTIME % 60 )) SECONDS";
+    [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} END: $(date +"${TIMESTAMP_OPTS}")";
+
+    [ ! -z "${KEYFILE}" ] && unset -v KEYFILE;
+    [ ! -z "${KEYSIZE}" ] && unset -v KEYSIZE;
+    [ ! -z "${RET_CODE}" ] && unset -v RET_CODE;
+    [ ! -z "${METHOD_NAME}" ] && unset -v METHOD_NAME;
+
+    return ${RETURN_CODE};
+}
diff --git a/functions.d/F09-network b/functions.d/F09-network
--- a/functions.d/F09-network
+++ b/functions.d/F09-network
@@ -831,7 +831,7 @@ function setProxy
     typeset RESOURCE_FILE="${HOME}/.etc/resources/${FUNCNAME[0]}";
     typeset -i DEFAULT_PORT=3128;
 
-	[ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${CNAME}" "${LINENO}" "RESOURCE_FILE -> ${RESOURCE_FILE}";
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${CNAME}" "${LINENO}" "RESOURCE_FILE -> ${RESOURCE_FILE}";
     [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${CNAME}" "${LINENO}" "DEFAULT_PORT -> ${DEFAULT_PORT}";
 
     while true
@@ -852,7 +852,7 @@ function setProxy
 
         [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${CNAME}" "${LINENO}" "ANSWER -> ${ANSWER}";
 
-		case "${ANSWER}" in
+        case "${ANSWER}" in
             [Xx]|[Qq]|[Cc])
                 ## user chose to quit, close us out
                 reset; clear;
@@ -881,7 +881,7 @@ function setProxy
 
                 return ${RETURN_CODE};
                 ;;
-			1)
+            1)
                 ## set proxy
                 while true
                 do
@@ -1122,7 +1122,7 @@ function setProxy
                 [ ! -z "${https_proxy}" ] && unset -v https_proxy;
                 [ ! -z "${ftp_proxy}" ] && unset -v ftp_proxy;
                 ;;
-		esac
+        esac
     done
 
     [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "RETURN_CODE -> ${RETURN_CODE}";
@@ -1142,3 +1142,186 @@ function setProxy
     return ${RETURN_CODE};
 }
 
+#=====  FUNCTION  =============================================================
+#          NAME:  checkSslExpiry
+#   DESCRIPTION:  Checks the SSL certificate expiration of a given host.
+#    PARAMETERS:  Service hostname
+#       RETURNS:  0 if success, non-zero otherwise
+#==============================================================================
+function checkSslExpiry
+{
+    trap '[ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] || set +x; [ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set +v; set -o noclobber' INT TERM EXIT;
+
+    [ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] && set -x || set +x;
+    [ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set -v || set +v;
+
+    set +o noclobber;
+    typeset METHOD_NAME="${0}#${FUNCNAME[0]}";
+    typeset -i RETURN_CODE=0;
+
+    [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} START: $(date +"${TIMESTAMP_OPTS}")";
+    [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i START_EPOCH=$(date +"%s");
+
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} -> enter";
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "Provided arguments: ${*}";
+
+    if [ ${#} -eq 0 ]
+    then
+        RETURN_CODE=3;
+
+        writeLogEntry "STDERR" "${METHOD_NAME} - Configure access to a newly provisioned host";
+        writeLogEntry "STDERR" "Usage: ${METHOD_NAME} [ website:port ]
+                -> The website and port number to verify. Format: site name:port number";
+
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "RETURN_CODE -> ${RETURN_CODE}";
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} -> exit";
+
+        [ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] && set +x;
+        [ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set +v;
+
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i END_EPOCH=$(date +"%s");
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i RUNTIME=$(( START_EPOCH - END_EPOCH ));
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} TOTAL RUNTIME: $(( RUNTIME / 60 )) MINUTES, TOTAL ELAPSED: $(( RUNTIME % 60 )) SECONDS";
+        [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} END: $(date +"${TIMESTAMP_OPTS}")";
+
+        [ ${ERROR_COUNT} -ne 0 ] && typeset -i ERROR_COUNT=0;
+        [ ! -z "${EXPIRY_EPOCH}" ] && unset -v EXPIRY_EPOCH;
+        [ ! -z "${SITE_LIST}" ] && unset -v SITE_LIST;
+        [ ! -z "${SITE}" ] && unset -v SITE;
+        [ ! -z "${SITE_HOSTNAME}" ] && unset -v SITE_HOSTNAME;
+        [ ! -z "${SITE_PORT}" ] && unset -v SITE_PORT;
+        [ ! -z "${RET_CODE}" ] && unset -v RET_CODE;
+        [ ! -z "${RETURNED_EXPIRY}" ] && unset -v RETURNED_EXPIRY;
+        [ ! -z "${EPOCH_EXPIRY}" ] && unset -v EPOCH_EXPIRY;
+
+        return ${RETURN_CODE};
+    fi
+
+    typeset -i EXPIRY_EPOCH=$(returnEpochTime "$(date +"%Y %m %d")" ${VALIDATION_PERIOD});
+    [ -f "${1}" ] && setArray SITE_LIST $(/usr/bin/env cat "${1}") || setArray SITE_LIST "${1}";
+
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "EXPIRY_EPOCH -> ${EXPIRY_EPOCH}";
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "SITE_LIST -> ${SITE_LIST}";
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "PORT_NUMBER -> ${PORT_NUMBER}";
+
+    for SITE in ${SITE_LIST[*]}
+    do
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "SITE -> ${SITE}";
+
+        typeset SITE_HOSTNAME="$(cut -d ":" -f 1 <<< "${SITE}")";
+        typeset -i SITE_PORT="$(cut -d ":" -f 2 <<< "${SITE}")";
+
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "SITE_HOSTNAME -> ${SITE_HOSTNAME}";
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "SITE_PORT -> ${SITE_PORT}";
+
+        ## make sure its a valid host
+        [ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] && set +x;
+        [ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set +v;
+
+        validateServerAvailability "${SITE_HOSTNAME}" ${SITE_PORT};
+        typeset -i RET_CODE=${?};
+
+        [ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] && set -x || set +x;
+        [ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set -v || set +v;
+
+        set +o noclobber;
+        typeset METHOD_NAME="${0}#${FUNCNAME[0]}";
+
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "RET_CODE -> ${RET_CODE}";
+
+        if [ -z "${RET_CODE}" ] || [ ${RET_CODE} -ne 0 ]
+        then
+            writeLogEntry "ERROR" "${METHOD_NAME}" "${0}" "${LINENO}" "Target host ${SITE_HOSTNAME} does not appear to be available.";
+            writeLogEntry "STDERR" "${METHOD_NAME}" "${0}" "${LINENO}" "Target host ${SITE_HOSTNAME} does not appear to be available.";
+
+            [ ! -z "${SITE}" ] && unset -v SITE;
+            [ ! -z "${SITE_HOSTNAME}" ] && unset -v SITE_HOSTNAME;
+            [ ! -z "${SITE_PORT}" ] && unset -v SITE_PORT;
+            [ ! -z "${RET_CODE}" ] && unset -v RET_CODE;
+            [ ! -z "${RETURNED_EXPIRY}" ] && unset -v RETURNED_EXPIRY;
+            [ ! -z "${EPOCH_EXPIRY}" ] && unset -v EPOCH_EXPIRY;
+
+            (( ERROR_COUNT += 1 ));
+
+            continue;
+        fi
+
+        typeset RETURNED_EXPIRY="$(printf "%s\n" "quit" | /usr/bin/env openssl s_client -connect "${SITE_HOSTNAME}:${SITE_PORT}" -nbio -mtu 1500 -bugs -rand file:${RANDOM_GENERATOR} 2>/dev/null | \
+            /usr/bin/env sed -ne "/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p" | /usr/bin/env openssl x509 -noout -subject -dates | /usr/bin/env grep notAfter | cut -d "=" -f 2 | \
+            /usr/bin/env awk '{print $4, $1, $2}')";
+
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "RETURNED_EXPIRY -> ${RETURNED_EXPIRY}";
+
+        if [ -z "${RETURNED_EXPIRY}" ]
+        then
+            writeLogEntry "ERROR" "${METHOD_NAME}" "${0}" "${LINENO}" "Failed to obtain SSL certificate information from ${SITE_HOSTNAME}. Please verify the hostname and port number, and re-try.";
+            writeLogEntry "STDERR" "${METHOD_NAME}" "${0}" "${LINENO}" "Failed to obtain SSL certificate information from ${SITE_HOSTNAME}. Please verify the hostname and port number, and re-try.";
+
+            [ ! -z "${SITE}" ] && unset -v SITE;
+            [ ! -z "${SITE_HOSTNAME}" ] && unset -v SITE_HOSTNAME;
+            [ ! -z "${SITE_PORT}" ] && unset -v SITE_PORT;
+            [ ! -z "${RET_CODE}" ] && unset -v RET_CODE;
+            [ ! -z "${RETURNED_EXPIRY}" ] && unset -v RETURNED_EXPIRY;
+            [ ! -z "${EPOCH_EXPIRY}" ] && unset -v EPOCH_EXPIRY;
+
+            (( ERROR_COUNT += 1 ));
+
+            continue;
+        fi
+
+        typeset -i EPOCH_EXPIRY=$(returnEpochTime "${RETURNED_EXPIRY}");
+
+        [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${CNAME}" "${LINENO}" "EPOCH_EXPIRY -> ${EPOCH_EXPIRY}";
+
+        if [ -z "${EPOCH_EXPIRY}" ]
+        then
+            writeLogEntry "ERROR" "${METHOD_NAME}" "${0}" "${LINENO}" "Failed to obtain an expiration date for the obtained certificate. Please ensure the data is correct.";
+            writeLogEntry "STDERR" "${METHOD_NAME}" "${0}" "${LINENO}" "Failed to obtain an expiration date for the obtained certificate. Please ensure the data is correct.";
+
+            [ ! -z "${SITE}" ] && unset -v SITE;
+            [ ! -z "${SITE_HOSTNAME}" ] && unset -v SITE_HOSTNAME;
+            [ ! -z "${SITE_PORT}" ] && unset -v SITE_PORT;
+            [ ! -z "${RET_CODE}" ] && unset -v RET_CODE;
+            [ ! -z "${RETURNED_EXPIRY}" ] && unset -v RETURNED_EXPIRY;
+            [ ! -z "${EPOCH_EXPIRY}" ] && unset -v EPOCH_EXPIRY;
+
+            (( ERROR_COUNT += 1 ));
+
+            continue;
+        fi
+
+        [ ${EPOCH_EXPIRY} -le ${EXPIRY_EPOCH} ] && writeLogEntry "STDOUT" "${METHOD_NAME}" "${CNAME}" "${LINENO}" "Certificate for host ${SITE_HOSTNAME} expires on ${RETURNED_EXPIRY}";
+
+        [ ! -z "${SITE}" ] && unset -v SITE;
+        [ ! -z "${SITE_HOSTNAME}" ] && unset -v SITE_HOSTNAME;
+        [ ! -z "${SITE_PORT}" ] && unset -v SITE_PORT;
+        [ ! -z "${RET_CODE}" ] && unset -v RET_CODE;
+        [ ! -z "${RETURNED_EXPIRY}" ] && unset -v RETURNED_EXPIRY;
+        [ ! -z "${EPOCH_EXPIRY}" ] && unset -v EPOCH_EXPIRY;
+    done
+
+    [ ${ERROR_COUNT} -ne 0 ] && typeset -i RETURN_CODE=${ERROR_COUNT} || typeset -i RETURN_CODE=0;
+
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "RETURN_CODE -> ${RETURN_CODE}";
+    [ ! -z "${ENABLE_DEBUG}" ] && [ "${ENABLE_DEBUG}" = "${_TRUE}" ] && writeLogEntry "DEBUG" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} -> exit";
+
+    [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i END_EPOCH=$(date +"%s");
+    [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && typeset -i RUNTIME=$(( START_EPOCH - END_EPOCH ));
+    [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} TOTAL RUNTIME: $(( RUNTIME / 60 )) MINUTES, TOTAL ELAPSED: $(( RUNTIME % 60 )) SECONDS";
+    [ ! -z "${ENABLE_PERFORMANCE}" ] && [ "${ENABLE_PERFORMANCE}" = "${_TRUE}" ] && writeLogEntry "PERFORMANCE" "${METHOD_NAME}" "${0}" "${LINENO}" "${METHOD_NAME} END: $(date +"${TIMESTAMP_OPTS}")";
+
+    [ ! -z "${ENABLE_VERBOSE}" ] && [ "${ENABLE_VERBOSE}" = "${_TRUE}" ] && set +x;
+    [ ! -z "${ENABLE_TRACE}" ] && [ "${ENABLE_TRACE}" = "${_TRUE}" ] && set +v;
+
+    [ ${ERROR_COUNT} -ne 0 ] && typeset -i ERROR_COUNT=0;
+    [ ! -z "${EXPIRY_EPOCH}" ] && unset -v EXPIRY_EPOCH;
+    [ ! -z "${SITE_LIST}" ] && unset -v SITE_LIST;
+    [ ! -z "${SITE}" ] && unset -v SITE;
+    [ ! -z "${SITE_HOSTNAME}" ] && unset -v SITE_HOSTNAME;
+    [ ! -z "${SITE_PORT}" ] && unset -v SITE_PORT;
+    [ ! -z "${RET_CODE}" ] && unset -v RET_CODE;
+    [ ! -z "${RETURNED_EXPIRY}" ] && unset -v RETURNED_EXPIRY;
+    [ ! -z "${EPOCH_EXPIRY}" ] && unset -v EPOCH_EXPIRY;
+
+    return ${RETURN_CODE};
+}
